name: stream_chat
homepage: https://github.com/GetStream/stream-chat-dart
description: The official Dart client for Stream Chat, a service for building chat applications.
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  logging: ^0.11.4
  dio: ^3.0.8
  web_socket_channel: ^1.1.0
  uuid: ^2.0.4
  async: ^2.4.0
  stream_channel: ^2.0.0

dev_dependencies:
  build_runner: ^1.7.0
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
  mockito: ^4.1.1
