name: stream_chat_dart
description: Workbench Flutter project to build Dart client

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  json_annotation: ^3.0.1
  http: 0.12.0
  logging: ^0.11.4

dev_dependencies:
  build_runner: ^1.7.0
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
