name: stream_chat
homepage: https://github.com/GetStream/stream-chat-dart
description: The official Dart client for Stream Chat, a service for building chat applications.
version: 0.1.19

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  logging: ^0.11.4
  dio: ^3.0.9
  web_socket_channel: ^1.1.0
  uuid: ^2.0.4
  async: ^2.4.0
  stream_channel: ^2.0.0
  rxdart: ^0.23.1
  moor: ^2.4.2
  moor_ffi: ^0.4.0
  path_provider: ^1.6.5
  path: ^1.6.4

dev_dependencies:
  build_runner: ^1.8.0
  json_serializable: ^3.2.5
  moor_generator: ^2.4.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
  mockito: ^4.1.1
