name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  test:
    container:
      image:  google/dart:latest
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2      
    - name: Get dependencies
      run: pub get
    - name: Run tests
      run: pub run test
