name: Example Github pages

on:
  push:
    branches:
      - master

env:
  flutter_version: "1.12.13+hotfix.5"

jobs:
  publish:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2  
    - name: Cache Flutter dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    - name: Flutter action
      uses: subosito/flutter-action@v1.1.1
      with:
        flutter-version: ${{ env.flutter_version }}
    - name: Get dependencies
      run: flutter pub get
    - name: Activate peanut
      run: flutter pub global activate peanut
    - name: Publish
      run: flutter pub global run peanut:peanut
