name: Example Github pages

on:
  push:
    branches:
      - master

env:
  flutter_version: "1.14.6"

jobs:
  publish:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2  
    - name: Cache Flutter dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
    - name: Flutter action
      uses: subosito/flutter-action@v1.1.1
      with:
        flutter-version: ${{ env.flutter_version }}
        channel: 'beta'
    - name: Activate web
      run: flutter config --enable-web
    - name: Github pages branch 
      run: |
        git checkout gh-pages
        git pull origin gh-pages
        git checkout master
    - name: Get dependencies
      run: flutter pub get
    - name: Activate peanut
      run: flutter pub global activate peanut
    - name: Set Github user
      run: |
        git config --global user.email "actions@getstream.io"
        git config --global user.name "Github actions"
    - name: Build
      run: flutter pub global run peanut:peanut
    - name: Publish
      run: |
        git checkout gh-pages
        git push origin gh-pages
